name: pubmed
channels:
  - conda-forge
  - defaults
dependencies:
  - beautifulsoup4=4.9.3
  - click=7.1.2
  - ipython=7.23.1
  - matplotlib=3.4.2
  - nltk=3.6.2
  - numpy=1.20.2
  - pandas=1.2.4
  - pillow=8.1.2
  - pip=21.1.1
  - python=3.9.2
  - requests=2.25.1
  - scikit-learn=0.24.2
  - scipy=1.6.3
  - seaborn=0.11.1
  - spacy=3.0.6
  - sympy=1.8
  - wordcloud=1.8.1
  - pip:
    - metapub==0.5.5
    - en-core-web-sm==3.0.0
